### ISSUE TITLE
Initialiser architecture du repo

### ISSUE THREAD

**Issue by clementbrizard** [timotheebeaugas/french-national-assembly-word-analysis#1]
On peut partir sur la structure suivante :
```
components/
  api.ts
  cron.ts
src/ 
  controllers/
  services/
  models/
app.ts // Pour lancer le serveur node.js
```

Le dossier  `models` peut nous servir pour déclarer nos modèles de données, comme ils le suggèrent dans [cet article](https://www.becomebetterprogrammer.com/typescript-organizing-and-storing-types-and-interfaces/).

**Comment by timotheebeaugas** [comment]
Dossiers créés

**Comment by timotheebeaugas** [comment]
Note pour plus tard : comment intégrer des dossiers vide dans un commit (mettre un fichier vide dedans ?)

**Comment by clementbrizard** [comment]
Yes @timotheebeaugas, tu peux créer un fichier `.gitkeep` dedans : https://www.freecodecamp.org/news/what-is-gitkeep/

**Comment by timotheebeaugas** [comment]
parfais!
