### ISSUE TITLE
Créer le parser

### ISSUE THREAD

**Issue by clementbrizard** [timotheebeaugas/french-national-assembly-word-analysis#2]
Dans les `services`, on peut se créer un dossier `Parser`, avec dedans une première classe `ParserAbstract` : une classe abstraite qui va définir les méthodes que ses classes filles devront implémenter. Elle peut disposer d'une méthode principale `run`, qui prend en paramètre un fichier. Le retour de la méthode `run` peut sans-doute être un objet Javascript qui contient toutes les iinformations du fichier parsé. Cette méthode `run` peut appeler plusieurs getters pour alimenter cet objet :

- `getDate` (date de la séance)
- `getTitle` (titre de la séance s'il y en a un)
- `getQuotes` : retourne l'ensemble des paroles prononcées pendant la séance, et leur auteur.

On peut ensuite définir dans ce même dossier `ParserXML`, une classe fille, qui hérite donc de `ParserAbstract`, et implémente les méthodes définies par `ParserAbstract`.

**Comment by clementbrizard** [comment]
Lien du code source pour voir le fonctionnement des classes abstraites et filles : https://paste.picasoft.net/?de32159741a47cea#BY4qUfSrACykL57Vp15hT9ezaEbrRYdgZoSCwGVaCPay

**Comment by timotheebeaugas** [comment]
Code source périmé.
Note pour plus tard : Revoir le fonctionnement des classes Parser, à partir du code actuel.
Question : Les méthodes doivent-elles renvoyer une réponse en cas de succès du parsing ?
